k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: o11n-eks-int-dh
  currentCluster: o11n-eks-int-dh
  clusters:
    o11n-eks-int-dh:
      namespace:
        active: ""
        favorites:
        - all
        - monitoring
        - default
      view:
        active: deployment
      featureGates:
        nodeShell: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
